=== harsha-pradhan/cia-lab/employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Emp-ID" type="xs:string"/>
                            <xs:element name="Emp-name" type="xs:string"/>
                            <xs:element name="Emp-age" type="xs:integer"/>
                            <xs:element name="Emp-salary" type="xs:integer"/>
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="50000"/>
                                    <xs:maxInclusive value="200000"/>
                                </xs:restriction>
                            </xs:simpleType>
                            <xs:element name="Emp-emailid" type="xs:string"/>
                            <xs:element name="Emp-Phonenum" type="xs:integer"/>
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:length value="10"/>
                                </xs:restriction>
                            </xs:simpleType>
                            <xs:element name="Emp-designation" type="xs:string"/></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== harsha-pradhan/cia-lab/employee.xml
/*HARSHA 2047229*/
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="employee.xsd">
	
	<employee>
	<Emp-ID> 201</Emp-ID>
		<Emp-name> HARSHIT</Emp-name>
		<Emp-age> 26</Emp-age> 
		<Emp-salary>40000 </Emp-salary>
		<Emp-emailid>harshit12@gmail.com</Emp-emailid>
		<Emp-Phonenum>9208734902</Emp-Phonenum>
		<Emp-designation> Junior manager</Emp-designation>
	</employee>
	<employee>
	<Emp-ID> 202</Emp-ID>
		<Emp-name> Akash</Emp-name>
		<Emp-age> 49</Emp-age> 
		<Emp-salary>45000 </Emp-salary>
		<Emp-emailid>Akash34@gmail.com</Emp-emailid>
		<Emp-Phonenum>9208784102</Emp-Phonenum>
		<Emp-designation> manager</Emp-designation>
	</employee>
	<employee>
	<Emp-ID> 203</Emp-ID>
		<Emp-name> Johnny</Emp-name>
		<Emp-age> 43</Emp-age> 
		<Emp-salary>55000 </Emp-salary>
		<Emp-emailid>johnny12@gmail.com</Emp-emailid>
		<Emp-Phonenum>9208964902</Emp-Phonenum>
		<Emp-designation>intern </Emp-designation>
	</employee>
	<employee>
	<Emp-ID> 204</Emp-ID>
		<Emp-name> Rahul</Emp-name>
		<Emp-age> 56</Emp-age> 
		<Emp-salary>60000</Emp-salary>
		<Emp-emailid>rahul1902@gmail.com</Emp-emailid>
		<Emp-Phonenum>9208734902</Emp-Phonenum>
		<Emp-designation> CEO</Emp-designation>
	</employee>
	
	
	
</company>
